### ISSUE TITLE
Weird corner data from JSON

### ISSUE THREAD

**Issue by ricerodriguez** [GregoryGregg/Dream_Team#5]
This was the data I got from running `rostopic echo /mapper/raw_data/corners` while the `jsong_writer` node is running.
```
---
TopL: 
  x: 16
  y: 177
TopR: 
  x: 410
  y: 167
BotL: 
  x: 421
  y: 149
BotR: 
  x: 8
  y: 165
---
```

It doesn't quite look right.
